apiVersion: v1
kind: Service

metadata:
  name: backend-service

spec:
  selector:
    app: backend

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080

  type: ClusterIP
root@ip-172-31-11-87:/var/lib/jenkins/workspace/event-planner-pipeline/k8s# cat frontend-service.yaml
apiVersion: v1
kind: Service

metadata:
  name: frontend-service

spec:
  selector:
    app: frontend

  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000

  type: ClusterIP