apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: mysql

spec:
  serviceName: mysql-service

  replicas: 1

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
        - name: mysql

          image: mysql:8.0

          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_DATABASE
              value: event_planner_DB

            - name: MYSQL_USER
              value: event_user

            - name: MYSQL_PASSWORD
              value: StrongPassword123

            - name: MYSQL_ROOT_PASSWORD
              value: SuperRootPassword

          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql

  volumeClaimTemplates:
    - metadata:
        name: mysql-storage

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 5Gi